apps/user/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from rest_framework import routers

from .views import ( 
    UserRegistrationView,
    ActivateAccount,
    UserLoginView,
    DashboardAdminView,
    AdminUserList,
    AdminCategoryList,
    AdminCategoryAdd,
    AdminNewsAdd,
    AdminNewsList,
    AdminNewsByCategoryList,
    UserDeleteAPIView
)

router = routers.DefaultRouter()

app_name = 'user'

urlpatterns = [
    path('register/', UserRegistrationView.as_view(), name='register'),
    path('login/', UserLoginView.as_view(template_name='users/login.html'), name='login'),
    path('activate/<uidb64>/<token>/', ActivateAccount.as_view(), name='activate'),
    path('admin-login/', UserLoginView.as_view(template_name='users/admin_login.html'), name='admin-login'),
    path('portal-admin/', DashboardAdminView.as_view(), name='portal-admin'),
    path('admin-user-list/', AdminUserList.as_view(), name='admin-user-list'),
    path('admin-category-list/', AdminCategoryList.as_view(), name='admin-category-list'),
    path('admin-news-list/', AdminNewsList.as_view(), name='admin-news-list'),
    path('admin-news-by-category/<slug:category_slug>/', AdminNewsByCategoryList.as_view(), name='admin-news-by-category'),
    path('admin-category-add/', AdminCategoryAdd.as_view(), name='admin-category-add'),
    path('admin-news-add/', AdminNewsAdd.as_view(), name='admin-news-add'),
    path('user-delete-api/<email>/delete/', UserDeleteAPIView.as_view(), name='user_delete_api'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

#from portal.forms import EmailValidationOnForgotPassword
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# REST
#from rest_framework import routers


#router = routers.DefaultRouter()

#handler404 = 'portal.views.handler404'
#handler500 = 'portal.views.handler500'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('apps.user.urls', 'user'), namespace='user')),
    path('', include(('apps.home.urls', 'home'), namespace='home')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# urlpatterns += staticfiles_urlpatterns()

apps/user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from .manager import CustomUserManager

from django.utils.translation import gettext_lazy as _

# Create your models here.
class User(AbstractUser):
    is_user = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)
    email_confirmed = models.BooleanField(default=False)

    username = None
    email = models.EmailField(_('email address'), unique=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.email


class NewsReader(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    is_active = models.BooleanField(default=False)

apps/user/forms.py
from urllib import request
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordResetForm
from apps.user.models import User, NewsReader
from django.db import transaction
from django.utils.translation import gettext_lazy as _
from django.contrib.auth import password_validation

class UserRegistrationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ['first_name', 'last_name', 'email', 'password1', 'password2']

    def save(self, commit=True):
        user = super().save(commit=False)
        user.is_user = True
        user.save()
        news_reader = NewsReader.objects.create(user=user)
        return user


class UserLoginForm(AuthenticationForm):
    user_type = forms.CharField(max_length=150)

    error_messages = {
        'invalid_login': _(
            "Please enter a correct %(username)s and password. Note that both "
            "fields may be case-sensitive."
        ),
        'invalid': _("Invalid user input!"),
        'inactive': _("This account is inactive."),
    }

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        user_type = self.cleaned_data.get('user_type')

        if username is not None and password:
            self.user_cache = authenticate(self.request, username=username, password=password)
            if self.user_cache is None:
                raise self.get_invalid_login_error()
            else:
                if self.user_cache.is_admin and user_type == 'admin':
                    self.confirm_login_allowed(self.user_cache)
                elif self.user_cache.is_user and user_type == 'user':
                    self.confirm_login_allowed(self.user_cache)
                else:
                    raise forms.ValidationError(
                        self.error_messages['invalid'],
                        code='invalid',
                    )

        return self.cleaned_data

class EmailValidationOnForgotPassword(PasswordResetForm):

    error_messages = {
        'unregistered': _("The email is not registered. Please register"),
    }

    def clean_email(self):
        email = self.cleaned_data['email']
        if not User.objects.filter(email__iexact=email, is_active=True).exists():
            raise forms.ValidationError(self.error_messages['unregistered'], code='unregistered',)

        return email

apps/user/views.py
from datetime import datetime
from django.urls import reverse_lazy
from django.views.generic import ListView
from django.shortcuts import redirect, render
from apps.user.models import User
from django.views.generic.edit import CreateView
from django.contrib.auth.views import LoginView, PasswordResetView
from django.utils.http import url_has_allowed_host_and_scheme
from apps.user.forms import UserLoginForm, UserRegistrationForm
from .decorators import admin_required, user_required
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from apps.home.models import Category, News
from django.db.models import Q

from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from .tokens import account_activation_token

from django.core.mail import send_mail
from django.db.models import Q
from django.shortcuts import get_object_or_404
from django.conf import settings

from django.utils.decorators import method_decorator
from django.views.generic import CreateView, ListView, UpdateView, TemplateView, View
from django.utils.encoding import force_str
from django.contrib.auth import login
from rest_framework.generics import DestroyAPIView


class UserDeleteAPIView(DestroyAPIView):
    queryset = User.objects.all()
    lookup_field = 'email'

# Create your views here.
class UserRegistrationView(CreateView):
    model = User
    form_class = UserRegistrationForm
    template_name = 'users/register.html'

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, {
            'form': form,
            'user_type': 'user',
        })

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():

            user = form.save(commit=False)
            user.is_active = False # Deactivate account till it is confirmed
            user.save()

            # current_site = get_current_site(request)
            # subject = 'Activate Your User account'
            # message = render_to_string('users/account_activation_email.html', {
            #     'user': user,
            #     'domain': current_site.domain,
            #     'uid': urlsafe_base64_encode(force_bytes(user.pk)),
            #     'token': account_activation_token.make_token(user),
            # })
            # user.email_user(subject, message, 'aqif.cse@gmail.com')

            # email_sent_message = 'An email has been sent to ' + str(user.email) + ' Please check your email and click on the confirmation link to confirm your account'

            return render(request, 'users/login.html', {
                'success_message': email_sent_message,
            })

        return render(request, self.template_name, {'form': form})

class ActivateAccount(View):

    def get(self, request, uidb64, token, *args, **kwargs):
        try:
            uid = force_str(urlsafe_base64_decode(uidb64))
            #print(uid)
            user = User.objects.get(pk=uid)

        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            #print("Does not exists")
            user = None

        if user is not None and account_activation_token.check_token(user, token):
            if user.is_user:
                user.is_active = True
            elif user.is_developer:
                user.is_active = False

            user.email_confirmed = True
            user.save()
            login(request, user)

            if user.is_user:
                user_success_account_message = email_sent_message = 'Hi!! ' + str(user.username) + ' Your account have been confirmed. Please log with your given username and password.'

                return render(request, 'users/login.html', {
                    'success_message': user_success_account_message,
                })
            elif user.is_developer:
                admin_approval_message = 'Hi ' + str(user.username) +'!! Please wait for the activation status email from the admin. Once you get it, you will be able to login with your given username and password.  '
                return render(request, 'users/login.html', {
                    'success_message': admin_approval_message,
                })            
        else:
            return render(request, 'users/login.html', {
                'error_message': 'The confirmation link was invalid, possibly because it has already been used.'
            })


class UserLoginView(LoginView):
    form_class = UserLoginForm

    def get_success_url(self):
        
        if self.request.user.is_admin:
            return reverse_lazy('user:portal-admin')
        elif self.request.user.is_user:
            return reverse_lazy('home:user-home')
        else:
            return reverse_lazy('home:user-home')

    def get_redirect_url(self):
        """Return the user-originating redirect URL if it's safe."""
        redirect_to = self.request.POST.get(
            self.redirect_field_name,
            self.request.GET.get(self.redirect_field_name, '')
        )
        url_is_safe = url_has_allowed_host_and_scheme(
            url=redirect_to,
            allowed_hosts=self.get_success_url_allowed_hosts(),
            require_https=self.request.is_secure(),
        )
        return redirect_to if url_is_safe else ''


@method_decorator([login_required, admin_required], name='dispatch')
class DashboardAdminView(ListView):
    model = User
    template_name = 'users/admin_portal.html'
    # context_object_name = 'apps'
    # ordering = ['date']

    def get_queryset(self):
        # total_download = App.objects.aggregate(Sum('downloads'))

        # #year_list = list(range(1990, 2041, 1))

        # queryset = {
        #     "total_upload" : App.objects.filter(is_active = True),
        #     "total_download": total_download['downloads__sum'],
        #     #"year_list": year_list
        # }
        # return queryset
        pass

@method_decorator([login_required, admin_required], name='dispatch')
class AdminUserList(ListView):
    model = User
    template_name = 'users/admin_user_list.html'
    context_object_name = 'user_obj'
    paginate_by = 10

    def get_queryset(self):
        form = self.request.GET.get('q')
        if form:
            return User.objects.filter(
                Q(user__username__icontains=form) | 
                Q(user__email__icontains=form) | 
                Q(user__first_name__icontains=form) | 
                Q(user__last_name__icontains=form)
            ).order_by('id')
        queryset = User.objects.all().order_by('id')
        return queryset

    def get_context_data(self, **kwargs):
        kwargs['q'] = self.request.GET.get('q')
        return super().get_context_data(**kwargs)

@method_decorator([login_required, admin_required], name='dispatch')
class AdminCategoryList(ListView):
    model = Category
    template_name = 'users/admin_category_list.html'
    context_object_name = 'categories'
    paginate_by = 10

    def get_queryset(self):
        form = self.request.GET.get('q')
        if form:
            return Category.objects.filter(
                Q(__icontains=form) | 
                Q(app_version_code__icontains=form) |
                Q(app_version_name__icontains=form) |
                Q(app_package_name__icontains=form) | 
                Q(app_short_description__icontains=form)
            ).order_by('id').reverse()
        queryset = Category.objects.all().order_by('id').reverse()
        return queryset

    def get_context_data(self, **kwargs):
        kwargs['q'] = self.request.GET.get('q')
        return super().get_context_data(**kwargs)

@method_decorator([login_required, admin_required], name='dispatch')
class AdminNewsList(ListView):
    model = News
    template_name = 'users/admin_news_list.html'
    context_object_name = 'news'
    paginate_by = 10

    def get_queryset(self):
        form = self.request.GET.get('q')
        if form:
            return News.objects.filter(
                Q(app__app_name__icontains=form) | 
                Q(app_version_code__icontains=form) |
                Q(app_version_name__icontains=form) |
                Q(app_package_name__icontains=form) | 
                Q(app_short_description__icontains=form)
            ).order_by('id').reverse()
        queryset = News.objects.all().order_by('id').reverse()
        return queryset

    def get_context_data(self, **kwargs):
        kwargs['q'] = self.request.GET.get('q')
        return super().get_context_data(**kwargs)

@method_decorator([login_required, admin_required], name='dispatch')
class AdminNewsByCategoryList(ListView):
    model = News
    template_name = 'users/admin_news_list.html'
    context_object_name = 'news'
    paginate_by = 10

    def get_queryset(self):
        form = self.request.GET.get('q')
        if form:
            return News.objects.filter(
                Q(app__app_name__icontains=form) | 
                Q(app_version_code__icontains=form) |
                Q(app_version_name__icontains=form) |
                Q(app_package_name__icontains=form) | 
                Q(app_short_description__icontains=form)
            ).order_by('id').reverse()
        category_slug = self.kwargs['category_slug']
        print(category_slug)
        queryset = News.objects.filter(category__category_slug=category_slug).order_by('id').reverse()
        return queryset

    def get_context_data(self, **kwargs):
        kwargs['q'] = self.request.GET.get('q')
        return super().get_context_data(**kwargs)

apps/user/templates/users/account_activation_email.html
{% autoescape off %}
Hi {{ user.username }},

Please click on the link below to confirm your registration:

http://{{ domain }}{% url 'user:activate' uidb64=uid token=token %}

Thank you.

Regards,
Team News Portal
{% endautoescape %}

apps/user/templates/users/admin_base.html
{% load static %}

<!DOCTYPE html>
<html lang="">
    <head>
        <meta charset="utf-8">
        <title>Retnews &#8211; Best news, blog & magazine template</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- favicon.ico in the root directory -->
        <link rel="apple-touch-icon" href="{% static 'icon.png' %}">
        <meta name="theme-color" content="#030303">
        <!-- google fonts -->
        <link
            href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,300;0,500;0,700;1,300;1,500&family=Poppins:ital,wght@0,300;0,500;0,700;1,300;1,400&display=swap"
            rel="stylesheet">
        <link href="{% static 'assets/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
        <link href="{% static 'css/styles.css' %}" rel="stylesheet">
        <link href="{% static 'assets/css/sb-admin-2.css' %}" rel="stylesheet">
    </head>
    <body>
        <!-- header -->
        <header class="bg-light">
            <!-- navbar -->
            <!-- Navbar menu  -->
            <div class="navigation-wrap navigation-shadow bg-white">
                <nav class="navbar navbar-hover navbar-expand-lg navbar-soft">
                    <div class="container">
                        <div class="offcanvas-header">
                            <div data-toggle="modal" data-target="#modal_aside_right" class="btn-md">
                                <span class="navbar-toggler-icon"></span>
                            </div>
                        </div>
                        <div class="collapse navbar-collapse justify-content-between" id="main_nav99">
                            <ul class="navbar-nav ml-auto ">
                                <li class="nav-item dropdown">
                                    <a class="nav-link active dropdown" href="{% url 'user:portal-admin' %}"> Portal </a>
                                </li>
                                <li class="nav-item dropdown">
                                    <a class="nav-link active dropdown" href="{% url 'user:admin-user-list' %}"> User List </a>
                                </li>
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown" href="{% url 'user:admin-category-list' %}"> Category List </a>
                                </li>
                                <li class="nav-item dropdown">
                                    <a class="nav-link" href="{% url 'user:admin-news-list' %}"> News List </a>
                                </li>
                            </ul>
                            {% block search %}
                            <!-- Search bar.// -->
                            <ul class="navbar-nav ">
                                <li class="nav-item search hidden-xs hidden-sm "> <a class="nav-link" href="#">
                                    <i class="fa fa-search"></i>
                                    </a>
                                </li>
                            </ul>
                            <!-- Search content bar.// -->
                            <div class="top-search navigation-shadow">
                                <div class="container">
                                    <div class="input-group ">
                                        <form action="#">
                                            <div class="row no-gutters mt-3">
                                                <div class="col">
                                                    <input class="form-control border-secondary border-right-0 rounded-0"
                                                        type="search" value="" placeholder="Search " id="example-search-input4">
                                                </div>
                                                <div class="col-auto">
                                                    <a class="btn btn-outline-secondary border-left-0 rounded-0 rounded-right"
                                                        href="/search-result.html">
                                                    <i class="fa fa-search"></i>
                                                    </a>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                            {% endblock %}
                            <!-- Search content bar.// -->
                        </div>
                        <!-- navbar-collapse.// -->
                    </div>
                </nav>
            </div>
            <!-- End Navbar menu  -->
            <!-- Navbar sidebar menu  -->
            
            <div id="modal_aside_right" class="modal fixed-left fade" tabindex="-1" role="dialog">
                <div class="modal-dialog modal-dialog-aside" role="document">
                    <div class="modal-content">
                        {% block search-sidebar %}
                        <div class="modal-header">
                            <div class="widget__form-search-bar  ">
                                <div class="row no-gutters">
                                    <div class="col">
                                        <input class="form-control border-secondary border-right-0 rounded-0" value="" placeholder="Search">
                                    </div>
                                    <div class="col-auto">
                                        <button class="btn btn-outline-secondary border-left-0 rounded-0 rounded-right">
                                        <i class="fa fa-search"></i>
                                        </button>
                                    </div>
                                </div>
                            </div>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        {% endblock %}
                        <div class="modal-body">
                            <nav class="list-group list-group-flush">
                                <ul class="navbar-nav ">
                                    <li class="nav-item dropdown">
                                        <a class="nav-link active text-dark" href="{% url 'user:portal-admin' %}"> Portal </a>
                                    </li>
                                    <li class="nav-item dropdown">
                                        <a class="nav-link active text-dark" href="{% url 'user:admin-user-list' %}"> User List </a>
                                    </li>
                                    <li class="nav-item dropdown">
                                        <a class="nav-link text-dark" href="{% url 'user:admin-category-list' %}"> Category List </a>
                                    </li>
                                    <li class="nav-item dropdown">
                                        <a class="nav-link active text-dark" href="{% url 'user:admin-news-list' %}" > News List </a>
                                    </li>
                                </ul>
                            </nav>
                        </div>
                        <div class="modal-footer">
                            <!-- <p>© 2020 <a href="http://retenvi.com" title="Premium WordPress news &amp; magazine theme">Magzrenvi</a>
                                -
                                Premium template news, blog & magazine &amp;
                                magazine theme by <a href="http://retenvi.com" title="retenvi">RETENVI.COM</a>. -->
                            <!-- </p> -->
                        </div>
                    </div>
                </div>
                <!-- modal-bialog .// -->
            </div>
            <!-- modal.// -->
            <!-- End Navbar sidebar menu  -->
            <!-- end navbar -->
        </header>
        <!-- end header -->

        {% block content %}{% endblock %}


        <!-- register -->
        <section class="wrapper__section p-0">
            <div class="wrapper__section__components">
            </div>
        </section>
        <a href="javascript:" id="return-to-top"><i class="fa fa-chevron-up"></i></a>
        <script type="text/javascript" src="{% static 'js/index.bundle.js' %}"></script>
        <!-- Bootstrap core JavaScript-->
        <script src="{% static 'assets/vendor/jquery/jquery.min.js' %}"></script>
        <!-- Core plugin JavaScript-->
        <script src="{% static 'assets/vendor/jquery-easing/jquery.easing.min.js' %}"></script>
        <!-- Custom scripts for all pages-->
        <script src="{% static 'assets/js/sb-admin-2.js' %}"></script>
        <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
        {% block script %}{% endblock %}
    </body>
</html>

apps/user/templates/users/admin_login.html
{% load static %}

<!DOCTYPE html>
<html lang="">

<head>
    <meta charset="utf-8">
    <title>Retnews &#8211; Best news, blog & magazine template</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- <link rel="manifest" href="site.webmanifest"> -->
    <!-- favicon.ico in the root directory -->
    <link rel="apple-touch-icon" href="{% static 'icon.png' %}">
    <meta name="theme-color" content="#030303">
    <!-- google fonts -->
    <link
        href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,300;0,500;0,700;1,300;1,500&family=Poppins:ital,wght@0,300;0,500;0,700;1,300;1,400&display=swap"
        rel="stylesheet">
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">
</head>

<body>
    <!-- header -->
    <header class="bg-light">

        <!-- modal.// -->
        <!-- End Navbar sidebar menu  -->
        <!-- end navbar -->
    </header>
    <!-- end header -->
    <section class="wrap__section">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <!-- Form Login -->
                    <div class="card mx-auto" style="max-width: 380px;">
                        <div class="card-body">
                            {% if form.non_field_errors %}
                            <div class="alert alert-{{ active.tags }}">
                                {{ form.non_field_errors }}
                            </div>
                            {% endif %}
                            <form method="post" action="{% url 'user:admin-login' %}">

                                {% csrf_token %}
                                <input type="hidden" name="user_type" value="admin" />
                                <div class="form-group">
                                    <input class="form-control" placeholder="Email" type="text" name="username">
                                </div>
                                <!-- form-group// -->
                                <div class="form-group">
                                    <input class="form-control" placeholder="Password" type="password" name="password">
                                </div>
                                <!-- form-group// -->
                                <!-- form-group form-check .// -->
                                <div class="form-group">
                                    <button type="submit" class="btn btn-primary btn-block"> Login </button>
                                </div>
                                <!-- form-group// -->
                            </form>
                        </div>
                        <!-- card-body.// -->
                    </div>
                    <!-- card .// -->
                </div>
            </div>
        </div>
    </section>
</body>

apps/user/templates/users/admin_portal.html
{% extends 'users/admin_base.html' %}

{% block content %}{% endblock %}

apps/user/templates/users/login.html
{% extends 'users/user_base.html' %}

{% block search %}{% endblock %}
{% block search-sidebar %}{% endblock %}

{% load crispy_forms_tags %}

{% block content %}
<section class="wrap__section">
    
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <!-- Form Login -->
                <div class="card mx-auto" style="max-width: 380px;">
                    <div class="card-body">
                        {% if form.non_field_errors %}
                        <div class="alert alert-{{ active.tags }}">
                        {{ form.non_field_errors }}
                        </div>
                        {% endif %}
                        <h4 class="card-title mb-4">Sign in</h4>
                        <form method="post" action="{% url 'user:login' %}">

                            {% csrf_token %}
                            <input type="hidden" name="user_type" value="user" />
                            <div class="form-group">
                                <input class="form-control" placeholder="Email" type="text" name="username">
                            </div>
                            <!-- form-group// -->
                            <div class="form-group">
                                <input class="form-control" placeholder="Password" type="password" name="password">
                            </div>
                            <!-- form-group// -->
                            <!-- form-group// -->
                            <div class="form-group">
                                <a href="#" class="float-right">Forgot password?</a>
                                <!-- <label class="float-left custom-control custom-checkbox"> <input type="checkbox"
                                    class="custom-control-input" checked="">
                                <span class="custom-control-label"> Remember </span> -->
                                </label>
                            </div>
                            <!-- form-group form-check .// -->
                            <div class="form-group">
                                <button type="submit" class="btn btn-primary btn-block"> Login </button>
                            </div>
                            <!-- form-group// -->
                        </form>
                    </div>
                    <!-- card-body.// -->
                </div>
                <!-- card .// -->
                <p class="text-center mt-4">Don't have account? <a href="{% url 'user:register' %}">Sign up</a></p>
            </div>
        </div>
    </div>
</section>
<!-- end login -->
{% endblock %}